/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    guides: Guide;
    reviews: Review;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    guides: GuidesSelect<false> | GuidesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'contacts-global': ContactsGlobal;
    'home-page': HomePage;
    'about-page': AboutPage;
  };
  globalsSelect: {
    'contacts-global': ContactsGlobalSelect<false> | ContactsGlobalSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  description: string;
  icon: 'Stethoscope' | 'Leaf' | 'Salad' | 'Pill' | 'Activity' | 'Dna' | 'Heart' | 'Brain' | 'Scale' | 'Microscope';
  color: 'green' | 'blue' | 'rose' | 'violet' | 'amber' | 'sky' | 'orange';
  /**
   * Произвольный текст: "от 4 500 ₽", "Бесплатно" и т.д.
   */
  price: string;
  duration: string;
  includes?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Если заполнено - отображается в углу карточки
   */
  tag?: string | null;
  /**
   * Меньше = выше. Верхние три карточки отображаются на главной странице
   */
  order?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides".
 */
export interface Guide {
  id: number;
  image: number | Media;
  title: string;
  /**
   * Отображается на карточке товара. ~150 символов.
   */
  description: string;
  /**
   * Отображается в модальном окне / на странице товара.
   */
  fullDescription: string;
  category: 'guides' | 'lectures' | 'checklists' | 'mini-courses';
  /**
   * Не обязательно для лекцией и видео-курсов
   */
  pages?: number | null;
  price: number;
  /**
   * Приватный файл - отправляется покупателю после оплаты
   */
  file?: (number | null) | Media;
  /**
   * Например: 4.9
   */
  rating?: number | null;
  review?: number | null;
  /**
   * Если заполнено - отображается в углу карточки
   */
  tag?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  name: string;
  age?: number | null;
  location?: string | null;
  text: string;
  stars: number;
  service: string;
  date: string;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'guides';
        value: number | Guide;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  icon?: T;
  color?: T;
  price?: T;
  duration?: T;
  includes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  tag?: T;
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides_select".
 */
export interface GuidesSelect<T extends boolean = true> {
  image?: T;
  title?: T;
  description?: T;
  fullDescription?: T;
  category?: T;
  pages?: T;
  price?: T;
  file?: T;
  rating?: T;
  review?: T;
  tag?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  name?: T;
  age?: T;
  location?: T;
  text?: T;
  stars?: T;
  service?: T;
  date?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Контакты изменяются во всех разделах сайта
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts-global".
 */
export interface ContactsGlobal {
  id: number;
  /**
   * Формат: 7XXXXXXXXXX. Не используйте плюс, пробел, скобки или дефисы - сайт сам сделает красивый вид номера
   */
  whatsapp: number;
  /**
   * Просто ник. Не используйте @ или https://t.me/ - сайт сам подставит необходимые символы
   */
  telegram: string;
  email: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero?: {
    badge?: string | null;
    heading?: string | null;
    headingAccent?: string | null;
    description?: string | null;
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    ctaLabel?: string | null;
  };
  about?: {
    image?: (number | null) | Media;
    imageTitle?: string | null;
    imageDescription?: string | null;
    heading?: string | null;
    paragraph1?: string | null;
    paragraph2?: string | null;
    checklistItem?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    ctaLabel?: string | null;
  };
  /**
   * Сами услуги настраиваются в отдельной категории
   */
  services?: {
    heading?: string | null;
    description?: string | null;
    ctaLabel?: string | null;
  };
  /**
   * Сами гайды и лекции настраиваются в отдельной категории
   */
  guides?: {
    heading?: string | null;
    description?: string | null;
    ctaLabel?: string | null;
  };
  howItWorks?: {
    heading?: string | null;
    description?: string | null;
    steps?:
      | {
          number: string;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Сами отзывы настраиваются в отдельной категории
   */
  reviews?: {
    heading?: string | null;
    description?: string | null;
    ctaLabel?: string | null;
  };
  proctolog?: {
    image?: (number | null) | Media;
    badge?: string | null;
    heading?: string | null;
    headingAccent?: string | null;
    paragraph1?: string | null;
    paragraph2?: string | null;
    checklistItem?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    ctaLabel?: string | null;
  };
  faq?: {
    heading?: string | null;
    items?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Сама форма настраивается в отдельной категории
   */
  consultation?: {
    heading?: string | null;
    description?: string | null;
  };
  /**
   * Сами контакты настраиваются в отдельной категории
   */
  contacts?: {
    heading?: string | null;
    description?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  hero?: {
    image?: (number | null) | Media;
    heading?: string | null;
    paragraph1?: string | null;
    paragraph2?: string | null;
    ctaLabel?: string | null;
  };
  values?: {
    heading?: string | null;
    items?:
      | {
          icon?: ('Heart' | 'BookOpen' | 'Award' | 'CheckCircle' | 'GraduationCap') | null;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  education?: {
    heading?: string | null;
    items?:
      | {
          image?: (number | null) | Media;
          year: string;
          title: string;
          place: string;
          variant: string;
          id?: string | null;
        }[]
      | null;
  };
  cta?: {
    heading?: string | null;
    description?: string | null;
    button?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts-global_select".
 */
export interface ContactsGlobalSelect<T extends boolean = true> {
  whatsapp?: T;
  telegram?: T;
  email?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        heading?: T;
        headingAccent?: T;
        description?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        ctaLabel?: T;
      };
  about?:
    | T
    | {
        image?: T;
        imageTitle?: T;
        imageDescription?: T;
        heading?: T;
        paragraph1?: T;
        paragraph2?: T;
        checklistItem?:
          | T
          | {
              text?: T;
              id?: T;
            };
        ctaLabel?: T;
      };
  services?:
    | T
    | {
        heading?: T;
        description?: T;
        ctaLabel?: T;
      };
  guides?:
    | T
    | {
        heading?: T;
        description?: T;
        ctaLabel?: T;
      };
  howItWorks?:
    | T
    | {
        heading?: T;
        description?: T;
        steps?:
          | T
          | {
              number?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  reviews?:
    | T
    | {
        heading?: T;
        description?: T;
        ctaLabel?: T;
      };
  proctolog?:
    | T
    | {
        image?: T;
        badge?: T;
        heading?: T;
        headingAccent?: T;
        paragraph1?: T;
        paragraph2?: T;
        checklistItem?:
          | T
          | {
              text?: T;
              id?: T;
            };
        ctaLabel?: T;
      };
  faq?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  consultation?:
    | T
    | {
        heading?: T;
        description?: T;
      };
  contacts?:
    | T
    | {
        heading?: T;
        description?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        image?: T;
        heading?: T;
        paragraph1?: T;
        paragraph2?: T;
        ctaLabel?: T;
      };
  values?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  education?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              image?: T;
              year?: T;
              title?: T;
              place?: T;
              variant?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        heading?: T;
        description?: T;
        button?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}