name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'

      - name: Start SSH Tunnel to Production DB
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

          export SSH_ASKPASS_REQUIRE=force
          echo -e '#!/bin/bash\necho "${{ secrets.PASSPHRASE }}"' > /tmp/askpass.sh
          chmod +x /tmp/askpass.sh
          export SSH_ASKPASS=/tmp/askpass.sh

          eval $(ssh-agent -s)
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
          echo "SSH_AGENT_PID=$SSH_AGENT_PID" >> $GITHUB_ENV

          setsid ssh-add ~/.ssh/id_rsa < /dev/null

          ssh -f -N -L 5432:127.0.0.1:5432 ${{ secrets.USERNAME }}@${{ secrets.HOST }}

      - name: Install dependencies
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
        run: npm ci

      - name: Run Payload migrations
        env:
          PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
        run: npx payload migrate
      
      - name: Build
        env:
          PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
          NEXT_PUBLIC_PAYLOAD_URL: ${{ secrets.NEXT_PUBLIC_PAYLOAD_URL }}
          NEXT_PUBLIC_SMARTCAPTCHA_CLIENT_KEY: ${{ secrets.NEXT_PUBLIC_SMARTCAPTCHA_CLIENT_KEY }}
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
        run: npm run build

      - name: Create deployment package
        run: |
          tar -czf deploy.tar.gz .next node_modules public package.json src

      - name: Copy archive to Server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "deploy.tar.gz"
          target: "/var/www/payload-app"

      - name: Deploy and Restart App via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd /var/www/payload-app
            pm2 stop payload-app || true
            rm -rf .next node_modules public src
            tar -xzf deploy.tar.gz
            rm deploy.tar.gz
            npx payload migrate
            pm2 start payload-app || pm2 start npm --name "payload-app" -- start